[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gbq_connector"
dynamic = ["version"]
description = "A wrapper for common Google Big Query Operations"
authors = [{ name = "Mark Young" }]
license = { text = "MIT" }
readme = "README.md"
requires-python = ">=3.11"

classifiers = [
    "Programming Language :: Python :: 3 :: Only",
]

dependencies = [
    "google-cloud-bigquery",
    "google-cloud-storage",
    "pyarrow",
    "google-auth",
    "pandas",
    "pandas-gbq",
    "db-dtypes",
    "requests",
    "pytz",
]

[project.optional-dependencies]
testing = [
    "tox>=4.0",
    "pytest>=7.0",
    "pytest-cov>=4.0",
]

[tool.setuptools]
package-dir = {"" = "src"}
packages = ["gbq_connector"]
zip-safe = false

[tool.setuptools.package-data]
gbq_connector = ["py.typed"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"