[build-system]
requires = ["setuptools>=64", "setuptools-scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "gbq-connector"
dynamic = ["version"]

[tool.setuptools_scm]
version_scheme = "no-guess-dev"
local_scheme = "no-local-version"

[tools.pytest.ini_options]
log_cli = true
log_cli_level = "INFO"
addopts = "--cov=gbq_connector"
testpaths = ["tests", "unit_tests"]